config/routes.rb
Rails.application.routes.draw do

resources :cocktails do
  resources :doses, only: [:create]
end
resources :doses, only: [:destroy]
root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find params[:id]
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def edit
    @cocktail = Cocktail.find params[:id]
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add a Cocktail", class: "btn btn-primary " %>
  <% end %>
</div>

app/views/cocktails/_form_dose.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.submit "add a Dose", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<h1>The best drinks in town:</h1>

<ul>

<% @cocktails.each do |drink| %>
  <li><%= link_to drink.name, cocktail_path(drink) %></li>
<% end %>

</ul>

<%= link_to "Create new Cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Create your favourite drink</h1>
<%= render "form" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.ingredient.name %> <%= dose.description %> | <%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ul>

<p>Ingredients:</p>
<%= render "cocktails/form_dose" %>

<%= link_to "Delete Cocktail", cocktail_path(@cocktail),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<%= link_to "See all Coacktails" , cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
</body>
  </body>
</html>